def misterious_error():
    a = 5

    return a.capitalize()